// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwt54Y4iSAR0WKGsFOCx4vIXDAj1EpcYU',
    appId: '1:973211419848:web:cad0e8a76dfb96d93f91fd',
    messagingSenderId: '973211419848',
    projectId: 'lovebug-monitoring-app',
    authDomain: 'lovebug-monitoring-app.firebaseapp.com',
    storageBucket: 'lovebug-monitoring-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vLbfKsFn3fVmTxhAzgAkx1gEftwXJpc',
    appId: '1:973211419848:android:e0b1206f7df513643f91fd',
    messagingSenderId: '973211419848',
    projectId: 'lovebug-monitoring-app',
    storageBucket: 'lovebug-monitoring-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJq375dMV_UDvkTlV3Or6F6qQK2SILBU',
    appId: '1:973211419848:ios:2ea7fe4cfec8c12d3f91fd',
    messagingSenderId: '973211419848',
    projectId: 'lovebug-monitoring-app',
    storageBucket: 'lovebug-monitoring-app.appspot.com',
    iosClientId: '973211419848-sqgpc0jip2drps6j648inl92temn1vse.apps.googleusercontent.com',
    iosBundleId: 'com.system.tech.nauti.lovebug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJq375dMV_UDvkTlV3Or6F6qQK2SILBU',
    appId: '1:973211419848:ios:2ea7fe4cfec8c12d3f91fd',
    messagingSenderId: '973211419848',
    projectId: 'lovebug-monitoring-app',
    storageBucket: 'lovebug-monitoring-app.appspot.com',
    iosClientId: '973211419848-sqgpc0jip2drps6j648inl92temn1vse.apps.googleusercontent.com',
    iosBundleId: 'com.system.tech.nauti.lovebug',
  );
}
